In [1]:
import numpy as np
import random 

In [2]:
movie_id = np.arange(start = 1301,stop =2302 )
movie_id

array([1301, 1302, 1303, ..., 2299, 2300, 2301])

In [3]:
user_id = np.arange(start =1,stop =101)
user_id

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
user_id_matrix = np.vstack(user_id)




In [5]:
user_id_matrix.shape

(100, 1)

In [6]:
movie_id_matrix= np.hstack(movie_id)
movie_id_matrix

array([1301, 1302, 1303, ..., 2299, 2300, 2301])

In [7]:
movie_id_matrix.shape

(1001,)

In [8]:
a = np.hsplit(movie_id_matrix,1001)
np.sort(a)

array([[1301],
       [1302],
       [1303],
       ...,
       [2299],
       [2300],
       [2301]])

In [9]:
arr_movieid = np.array(a).reshape(1,-1)
arr_movieid

array([[1301, 1302, 1303, ..., 2299, 2300, 2301]])

In [10]:
null_matrix = np.full(fill_value=-1,shape=(100,1000))
null_matrix


array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [11]:
for i in range(100):
    
    numberof_movies_byuser = np.random.randint(0,1000)
    
    index_of_movie_rated = np.random.randint(0,1000,size = numberof_movies_byuser)
    
    ratings_by_user = np.random.randint(0,11,size= numberof_movies_byuser)
    
    
    for j in range(numberof_movies_byuser):
        
        null_matrix[i][index_of_movie_rated[j]] = ratings_by_user[j]

In [12]:
null_matrix

array([[10, -1, -1, ...,  1, -1, 10],
       [ 4, -1, -1, ..., -1, -1, -1],
       [ 1, -1, -1, ..., -1,  5,  5],
       ...,
       [10, -1, -1, ...,  3,  6,  2],
       [-1, -1,  1, ..., -1,  6, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [13]:
new_null_arr = np.full(fill_value=-1,shape=(10,1000))

In [14]:
for i in range(10):
    
    numberof_movies_byuser = np.random.randint(0,1000)
    
    index_of_movie_rated = np.random.randint(0,1000,size = numberof_movies_byuser)
    
    ratings_by_user = np.random.randint(0,11,size= numberof_movies_byuser)
    
    
    for j in range(numberof_movies_byuser):
        
        new_null_arr[i][index_of_movie_rated[j]] = ratings_by_user[j]

In [15]:
new_null_arr

array([[-1, -1,  7, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1,  2, ..., -1,  0, -1],
       [-1, -1, -1, ..., -1, -1,  0],
       [-1, -1, -1, ..., -1, -1,  9]])

In [16]:
final_joined_arr = np.concatenate([null_matrix,new_null_arr],axis = 0)

In [17]:
final_joined_arr.shape

(110, 1000)

In [18]:
final_joined_arr.shape


(110, 1000)

In [19]:
more_50_movieID = np.arange(2302,2351)
more_50_movieID

array([2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312,
       2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323,
       2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334,
       2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345,
       2346, 2347, 2348, 2349, 2350])

In [20]:
new_movie_id = np.concatenate([movie_id_matrix,more_50_movieID],axis = 0)

In [21]:
new_null_arr_extra =np.full(fill_value=-1,shape=(110,50))
new_null_arr_extra.shape

(110, 50)

In [22]:
for i in range(110):
    
    numberof_movies_byuser = np.random.randint(0,50)
    
    index_of_movie_rated = np.random.randint(0,50,size = numberof_movies_byuser)
    
    ratings_by_user = np.random.randint(0,11,size= numberof_movies_byuser)
    
    
    for j in range(numberof_movies_byuser):
        
        new_null_arr_extra[i][index_of_movie_rated[j]] = ratings_by_user[j]

In [23]:
new_null_arr_extra.shape

(110, 50)

In [24]:
final_joined_arr_2 = np.concatenate([final_joined_arr,new_null_arr_extra],axis = 1,dtype ="float")
final_joined_arr_2

array([[10., -1., -1., ..., -1., -1., -1.],
       [ 4., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1.,  2., ..., 10., -1.,  4.],
       [-1., -1., -1., ...,  2., 10., -1.],
       [-1., -1., -1., ..., 10., -1.,  5.]])

In [25]:
final_joined_arr_2.shape

(110, 1050)

The final_joined_arr2 contains the ratings from 100 users + 10 experts. Each rating was given randomly to random movies


Now finding average ratings


In [26]:
final_joined_arr_2[final_joined_arr_2 ==-1] =np.nan

In [27]:
avg_rating_matrix = np.nanmean(final_joined_arr_2,axis = 0)

In [28]:
avg_rating_matrix

array([5.05      , 4.4       , 5.24324324, ..., 5.51282051, 5.85714286,
       3.97727273])

In [29]:
std_rating_matrix = np.nanstd(final_joined_arr_2,axis = 0)

In [30]:
std_rating_matrix

array([3.28595496, 3.22667454, 3.14002415, ..., 3.35789765, 2.94045209,
       3.06363299])

In [31]:
count_rating = final_joined_arr_2.shape[0] - np.sum(np.isnan(final_joined_arr_2),axis=0)

In [32]:
count_rating.shape
new_movie_id.shape

(1050,)

In [33]:
final_joined_arr_2 = np.vstack([new_movie_id,avg_rating_matrix,std_rating_matrix,count_rating])

In [34]:
final_joined_arr_2

array([[1301.        , 1302.        , 1303.        , ..., 2348.        ,
        2349.        , 2350.        ],
       [   5.05      ,    4.4       ,    5.24324324, ...,    5.51282051,
           5.85714286,    3.97727273],
       [   3.28595496,    3.22667454,    3.14002415, ...,    3.35789765,
           2.94045209,    3.06363299],
       [  40.        ,   35.        ,   37.        , ...,   39.        ,
          42.        ,   44.        ]])

In [35]:
final_joined_arr_2.shape

(4, 1050)

In [36]:
final_joined_arr_2 = final_joined_arr_2.transpose()

In [37]:
final_joined_arr_2.shape

(1050, 4)

In [38]:
import pandas as pd

In [39]:
pd.DataFrame(final_joined_arr_2,columns=['Movie_ID','Average_Rating','Standard_deviation_Rating','Count_of_Ratings_Given'])

Movie_ID  Average_Rating  Standard_deviation_Rating  \
0       1301.0        5.050000                   3.285955   
1       1302.0        4.400000                   3.226675   
2       1303.0        5.243243                   3.140024   
3       1304.0        5.600000                   2.835489   
4       1305.0        4.375000                   3.253364   
...        ...             ...                        ...   
1045    2346.0        4.976744                   3.259964   
1046    2347.0        4.947368                   3.068922   
1047    2348.0        5.512821                   3.357898   
1048    2349.0        5.857143                   2.940452   
1049    2350.0        3.977273                   3.063633   

      Count_of_Ratings_Given  
0                       40.0  
1                       35.0  
2                       37.0  
3                       40.0  
4                       40.0  
...                      ...  
1045                    43.0  
1046                    38.0  
1047                    39.0  
1048                    42.0  
1049                    44.0  

[1050 rows x 4 columns]

In [40]:
final_joined_arr_2 = np.sort(final_joined_arr_2,axis= 0)

# Bonus Question

In [41]:
final_joined_arr_2

array([[1.30100000e+03, 3.47222222e+00, 2.27901422e+00, 2.30000000e+01],
       [1.30200000e+03, 3.50000000e+00, 2.36985462e+00, 2.50000000e+01],
       [1.30300000e+03, 3.51282051e+00, 2.41091269e+00, 2.60000000e+01],
       ...,
       [2.34800000e+03, 6.33333333e+00, 3.74749309e+00, 5.10000000e+01],
       [2.34900000e+03, 6.43243243e+00, 3.79322705e+00, 5.10000000e+01],
       [2.35000000e+03, 6.43243243e+00, 3.87120471e+00, 5.10000000e+01]])

In [42]:
np.save("Numpy case study Result.npy",final_joined_arr_2)